[tool.cibuildwheel]

build-verbosity = 1

test-command = "py.test {package}"
test-requires = [
    "Cython>=0.24,<0.30",
    "click",
    "wheel",
    "Sphinx==1.8.1",
    "docutils<0.13.1",
    "mock",
    "pytest<6.0.0",
]

[build-system]
requires = [
    "Cython>=0.24,<0.30",
    "PyOpenGL",
    "glfw",
    "wheel",
    "click",
    "setuptools",
]
build-backend = "setuptools.build_meta"
